<?php

namespace repositories;

use Doctrine\ORM\EntityRepository,
	Doctrine\ORM\Query;
	

/**
 * EcorregionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EcorregionRepository extends EntityRepository
{
	
	/**
	 * Obtener todos las ecorregiones
	 * @return Array de Ecorregiones
	 */
	 public function getAll()
	 {
	 	$query = $this->_em->createQuery(
			"SELECT e FROM entities\Ecorregion e"
		);
		return $query->getResult(Query::HYDRATE_ARRAY);
	 }
}