<?php

namespace repositories;

use Doctrine\ORM\EntityRepository,
	Doctrine\ORM\Query;
	

/**
 * EcosistemaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EcosistemaRepository extends EntityRepository
{
	
	/**
	 * Obtener todos los Ecosistemas
	 * @return Array de objetos Ecosistema
	 */
	 public function getAll()
	 {
	 	$query = $this->_em->createQuery(
			"SELECT e 
			FROM entities\Ecosistema e"
		);
		return $query->getResult(Query::HYDRATE_OBJECT);
	 }
	 
	 public function getAllChildren()
	{
		$dql = "SELECT e FROM entities\Ecosistema e JOIN e.parent p WHERE p.id IS NOT NULL";
		$query = $this->_em->createQuery($dql);
		return $query->getResult(Query::HYDRATE_ARRAY);
	}
}