<?php

namespace repositories;

use Doctrine\ORM\EntityRepository,
	Doctrine\ORM\Query;
	

/**
 * EcosistemaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EcosistemaRepository extends EntityRepository
{
	
	/**
	 * Obtener todos los Ecosistemas
	 * @return Array de Ecosistema
	 */
	 public function getAll()
	 {
	 	$query = $this->_em->createQuery(
			"SELECT e 
			FROM entities\Ecosistema e
			WHERE e.parent IS NULL"
		);
		return $query->getResult(Query::HYDRATE_ARRAY);
	 }
}