<?php

namespace repositories;

use Doctrine\ORM\EntityRepository,
	Doctrine\ORM\Query;
	

/**
 * EstadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadoRepository extends EntityRepository
{
	/**
	 * Busqueda de estados de un taxon
	 * @param $taxon_name = Nombre del taxon
	 * @return Array de Estados
	 */
	public function searchEstados($taxon_name)
	{
		$dql = "SELECT e.name
				FROM entities\Estado e
				INNER JOIN e.localidad l
				INNER JOIN l.taxons t
				WHERE t.name = :name 
				GROUP BY e.name";
		$query = $this->_em->createQuery($dql);
		$query->setParameter('name', $taxon_name);
		
		return $query->getResult(Query::HYDRATE_ARRAY);
	}
	
}