<?php

namespace repositories;

use Doctrine\ORM\EntityRepository;

/**
 * HabitoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HabitoRepository extends EntityRepository
{
}