<?php

namespace repositories;

use Doctrine\ORM\EntityRepository,
	Doctrine\ORM\Query;
	

/**
 * MunicipioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MunicipioRepository extends EntityRepository
{
	
	/**
	 * Obtener todos los municipios de un estado
	 * @return Array de municipios
	 */
	 public function getAllByState($state)
	 {
	 	$query = $this->_em->createQuery(
			"SELECT m FROM entities\Municipio m JOIN m.estado e WHERE e.id = :stateid"
		);
		$query->setParameter('stateid', $state);
		return $query->getResult(Query::HYDRATE_ARRAY);
	 }
	 
}