<?php

namespace repositories;

use Doctrine\ORM\EntityRepository,
	Doctrine\ORM\Query;
	

/**
 * EstadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicacionRepository extends EntityRepository
{
	/**
	 * Busqueda de estados de un taxon
	 * @param $taxon_name = Nombre del taxon
	 * @return Array de Estados
	 */
	public function searchPublicaciones($taxon_name)
	{
		$dql = "SELECT p
				FROM entities\Publicacion p
				INNER JOIN p.localidades l
				INNER JOIN l.taxon t 
				WHERE t.name = :name
				GROUP BY p.title";
		$query = $this->_em->createQuery($dql);
		$query->setParameter('name', $taxon_name);
		
		return $query->getResult(Query::HYDRATE_OBJECT);
	}
	
	public function getAll()
	{
		$query = $this->_em->createQuery(
			"SELECT p FROM entities\Publicacion p"
		);
		return $query->getResult(Query::HYDRATE_ARRAY);
	}
	
}