<?php

namespace repositories;

use Doctrine\ORM\EntityRepository,
	Doctrine\ORM\Query;
	

/**
 * SustratoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SustratoRepository extends EntityRepository
{
	/**
	 * Obtener todos los sustratos
	 * @return Array de objetos Sustratos
	 */
	public function getAll()
	{
		$dql = "SELECT s
				FROM entities\Sustrato s";
		
		$query = $this->_em->createQuery($dql);
		
		return $query->getResult(Query::HYDRATE_OBJECT);
	}
	
}