<?php

namespace repositories;

use Doctrine\ORM\EntityRepository;

/**
 * SustratoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SustratoRepository extends EntityRepository
{
}