<?php

namespace repositories;

use Doctrine\ORM\EntityRepository,
	Doctrine\ORM\Query;
	

/**
 * SustratoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SustratoRepository extends EntityRepository
{
	/**
	 * Obtener todos los sustratos hijos
	 * @return Array de Sustratos
	 */
	public function getAll()
	{
		$dql = "SELECT s
				FROM entities\Sustrato s
				WHERE s.parent IS NULL";
		
		$query = $this->_em->createQuery($dql);
		//$query->setParameter('id', NULL);
		
		return $query->getResult(Query::HYDRATE_ARRAY);
	}
	
}