<?php

namespace repositories;

use Doctrine\ORM\EntityRepository,
	Doctrine\ORM\Query;
	

/**
 * TaxonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxonRepository extends EntityRepository
{
	/**
	 * Obtener todos los taxones
	 * @return Array de taxones 
	 */
	public function getAll()
	{
		$query = $this->_em->createQuery(
			"SELECT t FROM entities\Taxon t WHERE t.rank > 0"
		);
		return $query->getResult(Query::HYDRATE_ARRAY);
	}
	
	/**
	 * Busqueda por nombre del Taxon
	 * @param $taxon_name = Nombre del taxon. $exact = Busqueda aproximada o exacta
	 * @return Array de taxones 
	 */
	public function searchTaxonName($taxon_name, $exact = FALSE)
	{
		if ($exact) {
			$query = $this->_em->createQuery(
				"SELECT t FROM entities\Taxon t WHERE CONCAT(t.name, CONCAT(' ', t.authorInitials)) = :name AND t.rank IN(6,7,8) ORDER BY t.name"
			);
			$query->setParameter('name', $taxon_name);
		}
		else {
			$query = $this->_em->createQuery(
				"SELECT t FROM entities\Taxon t WHERE CONCAT(t.name, CONCAT(' ', t.authorInitials)) LIKE :name AND t.rank IN(6,7,8) ORDER BY t.name"
			);
			$query->setParameter('name', "%$taxon_name%");
		}
		return $query->getResult(Query::HYDRATE_ARRAY);
	}
	
	/**
	 * Obtener todos los taxones tengan imágenes
	 * @return Array de objetos tipo taxon
	 */
	public function getTaxonWithImages()
	{
		$query = $this->_em->createQuery(
			"SELECT t FROM entities\Taxon t WHERE t.images = :option"
		);
		$query->setParameter('option', TRUE);
		return $query->getResult(Query::HYDRATE_OBJECT);
	}
	
	/**
	 * Contar los taxones de un rank determinado
	 * @param $rank = Rank del taxón
	 * @return Cantidad de taxones del rank determinado
	 */
	public function rankCount($rank)
	{
		$query = $this->_em->createQuery(
			"SELECT COUNT(t.id) FROM entities\Taxon t WHERE t.rank = :rank"
		);
		$query->setParameter('rank', $rank);
		return $query->getResult(Query::HYDRATE_SINGLE_SCALAR);
	}
	
	public function getAllParentTaxon($parentRank)
	{
		$query = $this->_em->createQuery(
			"SELECT t.id, t.name FROM entities\Taxon t WHERE t.rank = :rank ORDER BY t.name"
		);
		$query->setParameter('rank', $parentRank);
		return $query->getResult(Query::HYDRATE_ARRAY);
	}
	
}