<?php

namespace repositories;

use Doctrine\ORM\EntityRepository;

/**
 * TaxonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxonRepository extends EntityRepository
{
	//General approximate search
	public function getTaxonsLike($taxon_name)
	{
		$qb = $this->getEntityManager()->createQueryBuilder();
		$qb->select('t')
			 ->from('models\Taxon', 't')
			 ->where($qb->expr()->like('t.name', '%'.$taxon_name.'%'));
			 
		return $qb->getQuery()->getArrayResult();
	}
}
