<?php

namespace repositories;

use Doctrine\ORM\EntityRepository,
	Doctrine\ORM\Query;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	public function getAll()
	{
		$query = $this->_em->createQuery(
			"SELECT u FROM entities\User u"
		);
		return $query->getResult(Query::HYDRATE_ARRAY);
	}
}